name: somatic_n-of-1
channels:
  - conda-forge
  - r
  - pcgr
  - bioconda
  - anaconda
  - defaults
dependencies:
  - ascat=2.5.1
  - bam-readcount=0.8
  - bbmap=38.57
  - bcftools=1.9
  - bedtools=2.28.0
  - bioconductor-biomart
  - bioconductor-bsgenome
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-customprodb
  - bioconductor-ensembldb
  - bioconductor-ensemblvep
  - bioconductor-genomicranges
  - bioconductor-org.hs.eg.db
  - bioconductor-purecn
  - bioconductor-qdnaseq
  - bwa=0.7.17
  - cancerit-allelecount=4.0.2
  - cpsr=0.5.2.2
  - crcmod=1.7
  - ensembl-vep=98.3
  - fastp=0.20.0
  - fastqc=0.11.8
  - gatk4=4.1.3.0
  - htslib=1.9
  - libiconv=1.15
  - msisensor=0.5
  - multiqc=1.7
  - nextflow=19.10.0
  - octopus=0.5.2b
  - pcgr=0.8.4.4
  - perl=5.26.2
  - picard=2.20.3=0
  - pisces=5.2.9.122
  - r-data.table
  - r-facets=0.5.14
  - r-plyr
  - r-dplyr
  - r-ggrepel
  - r-pheatmap
  - r-sequenza=2.1.2
  - r-tidyverse
  - samtools=1.9
  - snp-pileup=0.5.14
  - ucsc-liftover=377
  - varlociraptor=1.5.0
  - varscan=2.4.3
